LARGURAJANELA = 600  # largura da janela
ALTURAJANELA = 600  # altura da janela
CORTEXTO = (255, 255, 255)  # cor do texto (branca)
QPS = 60  # quadros por segundo
TAMMINIMO = 40  # tamanho mínimo do inimigo
TAMMAXIMO = 40  # tamanho máximo do inimigo
VELMINIMA = 1  # velocidade mínima do inimigo
VELMAXIMA = 8  # velocidade máxima do inimigo
ITERACOES = 6  # número de iterações antes de criar um novo inimigo
VELJOGADOR = 5  # velocidade da nave